// Sample crypto-KOL dataset powering the Kolio discovery preview mockup.
// Original mock data (no real persons); avatars use neutral placeholders.
export type Reel = { title: string; likes: number };
export type GenderSlice = { label: string; value: number };
export type Country = { name: string; weight: number };
export type Profile = {
  rank: number; name: string; username: string; bio: string;
  followers: number; engagementRate: number; fakeFollowers: number;
  averageReelPlays: number; location: string; verified: boolean;
  picture: string; platform: string; niche: string;
  gender: GenderSlice[]; countries: Country[]; reels: Reel[];
};

export const profiles: Profile[] = [
  {"rank":1,"name":"Daniel Okafor","username":"0xMaximalist","bio":"DeFi • NFT curator + community builder. Covering art, mints, and on-chain culture.","followers":1281670,"engagementRate":0.0651,"fakeFollowers":0.1119,"averageReelPlays":271575,"location":"Singapore","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio0","platform":"tiktok","niche":"DeFi","gender":[{"label":"male","value":0.6383},{"label":"female","value":0.3617}],"countries":[{"name":"United States","weight":0.4557},{"name":"Singapore","weight":0.0401},{"name":"Vietnam","weight":0.2996},{"name":"Japan","weight":0.069},{"name":"Nigeria","weight":0.1356}],"reels":[{"title":"DeFi: what most people get wrong","likes":66749},{"title":"Onchain breakdown of this week's flows","likes":50062}]},
  {"rank":2,"name":"Lily Chen","username":"defidan","bio":"NFTs • Daily trading breakdowns & market structure. Charts, not hopium.","followers":15185,"engagementRate":0.0625,"fakeFollowers":0.0197,"averageReelPlays":1558,"location":"France","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio1","platform":"x","niche":"NFTs","gender":[{"label":"male","value":0.662},{"label":"female","value":0.338}],"countries":[{"name":"Germany","weight":0.4218},{"name":"Singapore","weight":0.1443},{"name":"Nigeria","weight":0.2315},{"name":"Turkey","weight":0.0969},{"name":"UAE","weight":0.1055}],"reels":[{"title":"NFTs: what most people get wrong","likes":759},{"title":"Onchain breakdown of this week's flows","likes":569}]},
  {"rank":3,"name":"Omar Haddad","username":"L2_lily","bio":"L2 / scaling • Onchain analytics. Wallet flows, smart-money tracking, dashboards.","followers":373622,"engagementRate":0.0764,"fakeFollowers":0.1248,"averageReelPlays":117514,"location":"United States","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio2","platform":"youtube","niche":"L2 / scaling","gender":[{"label":"male","value":0.7178},{"label":"female","value":0.2822}],"countries":[{"name":"Brazil","weight":0.1528},{"name":"Vietnam","weight":0.459},{"name":"Turkey","weight":0.2302},{"name":"United Kingdom","weight":0.0939},{"name":"UAE","weight":0.0641}],"reels":[{"title":"L2 / scaling: what most people get wrong","likes":22836},{"title":"Onchain breakdown of this week's flows","likes":17127}]},
  {"rank":4,"name":"Sora Tanaka","username":"onchain_omar","bio":"Trading • Stablecoins & payments. RWA, treasuries, and the on-chain dollar.","followers":14256,"engagementRate":0.037,"fakeFollowers":0.0832,"averageReelPlays":4310,"location":"France","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio3","platform":"tiktok","niche":"Trading","gender":[{"label":"male","value":0.5698},{"label":"female","value":0.4302}],"countries":[{"name":"France","weight":0.0211},{"name":"Vietnam","weight":0.4012},{"name":"Germany","weight":0.316},{"name":"Brazil","weight":0.0549},{"name":"Singapore","weight":0.2068}],"reels":[{"title":"Trading: what most people get wrong","likes":422},{"title":"Onchain breakdown of this week's flows","likes":316}]},
  {"rank":5,"name":"Mia Novak","username":"satoshi_sora","bio":"Bitcoin • Onchain analytics. Wallet flows, smart-money tracking, dashboards.","followers":1795740,"engagementRate":0.0854,"fakeFollowers":0.0532,"averageReelPlays":313506,"location":"UAE","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio4","platform":"youtube","niche":"Bitcoin","gender":[{"label":"male","value":0.6763},{"label":"female","value":0.3237}],"countries":[{"name":"Brazil","weight":0.0265},{"name":"France","weight":0.442},{"name":"Vietnam","weight":0.1803},{"name":"Japan","weight":0.1553},{"name":"UAE","weight":0.1959}],"reels":[{"title":"Bitcoin: what most people get wrong","likes":122685},{"title":"Onchain breakdown of this week's flows","likes":92014}]},
  {"rank":6,"name":"Viktor Petrov","username":"gmGwei","bio":"Gaming / GameFi • Daily trading breakdowns & market structure. Charts, not hopium.","followers":744242,"engagementRate":0.0486,"fakeFollowers":0.1044,"averageReelPlays":429644,"location":"United Kingdom","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio5","platform":"x","niche":"Gaming / GameFi","gender":[{"label":"male","value":0.5019},{"label":"female","value":0.4981}],"countries":[{"name":"South Korea","weight":0.1445},{"name":"United States","weight":0.3281},{"name":"United Kingdom","weight":0.0126},{"name":"Nigeria","weight":0.0098},{"name":"Turkey","weight":0.505}],"reels":[{"title":"Gaming / GameFi: what most people get wrong","likes":28936},{"title":"Onchain breakdown of this week's flows","likes":21702}]},
  {"rank":7,"name":"Ava Lindqvist","username":"merkle_mia","bio":"Memecoins • L2 & scaling explainers. Builder-friendly. Rollups, data availability, ZK.","followers":2304603,"engagementRate":0.0495,"fakeFollowers":0.0157,"averageReelPlays":1294713,"location":"United Kingdom","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio6","platform":"tiktok","niche":"Memecoins","gender":[{"label":"male","value":0.7337},{"label":"female","value":0.2663}],"countries":[{"name":"Japan","weight":0.4655},{"name":"Brazil","weight":0.1214},{"name":"France","weight":0.0196},{"name":"United States","weight":0.1991},{"name":"Singapore","weight":0.1944}],"reels":[{"title":"Memecoins: what most people get wrong","likes":91262},{"title":"Onchain breakdown of this week's flows","likes":68447}]},
  {"rank":8,"name":"Pete Rourke","username":"validator_vik","bio":"Research • Onchain analytics. Wallet flows, smart-money tracking, dashboards.","followers":682801,"engagementRate":0.0129,"fakeFollowers":0.1021,"averageReelPlays":187339,"location":"Germany","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio7","platform":"x","niche":"Research","gender":[{"label":"male","value":0.7786},{"label":"female","value":0.2214}],"countries":[{"name":"Singapore","weight":0.3466},{"name":"Turkey","weight":0.3747},{"name":"Vietnam","weight":0.0283},{"name":"Germany","weight":0.1054},{"name":"UAE","weight":0.145}],"reels":[{"title":"Research: what most people get wrong","likes":7047},{"title":"Onchain breakdown of this week's flows","likes":5285}]},
  {"rank":9,"name":"Zara Malik","username":"airdrop_ava","bio":"RWA • L2 & scaling explainers. Builder-friendly. Rollups, data availability, ZK.","followers":3162816,"engagementRate":0.0459,"fakeFollowers":0.0911,"averageReelPlays":1249238,"location":"United States","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio8","platform":"youtube","niche":"RWA","gender":[{"label":"male","value":0.7395},{"label":"female","value":0.2605}],"countries":[{"name":"Germany","weight":0.3947},{"name":"United Kingdom","weight":0.0952},{"name":"UAE","weight":0.063},{"name":"Turkey","weight":0.0131},{"name":"South Korea","weight":0.434}],"reels":[{"title":"RWA: what most people get wrong","likes":116139},{"title":"Onchain breakdown of this week's flows","likes":87104}]},
  {"rank":10,"name":"Neo Park","username":"perps_pete","bio":"Stablecoins • GameFi & on-chain gaming. Reviews, playtests, and tokenomics teardowns.","followers":70628,"engagementRate":0.0861,"fakeFollowers":0.0555,"averageReelPlays":29828,"location":"Singapore","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio9","platform":"tiktok","niche":"Stablecoins","gender":[{"label":"male","value":0.8319},{"label":"female","value":0.1681}],"countries":[{"name":"Japan","weight":0.2695},{"name":"Vietnam","weight":0.1723},{"name":"Turkey","weight":0.232},{"name":"Singapore","weight":0.0374},{"name":"UAE","weight":0.2888}],"reels":[{"title":"Stablecoins: what most people get wrong","likes":4865},{"title":"Onchain breakdown of this week's flows","likes":3649}]},
  {"rank":11,"name":"Yuki Sato","username":"zk_zara","bio":"DeFi • L2 & scaling explainers. Builder-friendly. Rollups, data availability, ZK.","followers":37571,"engagementRate":0.0436,"fakeFollowers":0.0466,"averageReelPlays":17197,"location":"South Korea","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio10","platform":"youtube","niche":"DeFi","gender":[{"label":"male","value":0.5555},{"label":"female","value":0.4445}],"countries":[{"name":"United Kingdom","weight":0.268},{"name":"Germany","weight":0.0228},{"name":"Nigeria","weight":0.1192},{"name":"France","weight":0.2478},{"name":"Japan","weight":0.3422}],"reels":[{"title":"DeFi: what most people get wrong","likes":1310},{"title":"Onchain breakdown of this week's flows","likes":983}]},
  {"rank":12,"name":"Ben Adler","username":"nakamoto_neo","bio":"NFTs • GameFi & on-chain gaming. Reviews, playtests, and tokenomics teardowns.","followers":16100,"engagementRate":0.0736,"fakeFollowers":0.1504,"averageReelPlays":5739,"location":"Nigeria","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio11","platform":"x","niche":"NFTs","gender":[{"label":"male","value":0.8484},{"label":"female","value":0.1516}],"countries":[{"name":"South Korea","weight":0.0434},{"name":"Nigeria","weight":0.4263},{"name":"Vietnam","weight":0.0836},{"name":"United States","weight":0.1531},{"name":"United Kingdom","weight":0.2936}],"reels":[{"title":"NFTs: what most people get wrong","likes":948},{"title":"Onchain breakdown of this week's flows","likes":711}]},
  {"rank":13,"name":"Dora Costa","username":"yield_yuki","bio":"L2 / scaling • Onchain analytics. Wallet flows, smart-money tracking, dashboards.","followers":68909,"engagementRate":0.0665,"fakeFollowers":0.0435,"averageReelPlays":37961,"location":"France","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio12","platform":"youtube","niche":"L2 / scaling","gender":[{"label":"male","value":0.8001},{"label":"female","value":0.1999}],"countries":[{"name":"Vietnam","weight":0.2127},{"name":"Germany","weight":0.1443},{"name":"South Korea","weight":0.29},{"name":"Nigeria","weight":0.1139},{"name":"UAE","weight":0.2391}],"reels":[{"title":"L2 / scaling: what most people get wrong","likes":3666},{"title":"Onchain breakdown of this week's flows","likes":2749}]},
  {"rank":14,"name":"Rio Santos","username":"bridge_ben","bio":"Trading • NFT curator + community builder. Covering art, mints, and on-chain culture.","followers":14188,"engagementRate":0.0137,"fakeFollowers":0.0895,"averageReelPlays":4686,"location":"Turkey","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio13","platform":"tiktok","niche":"Trading","gender":[{"label":"male","value":0.8184},{"label":"female","value":0.1816}],"countries":[{"name":"United States","weight":0.1159},{"name":"Japan","weight":0.1025},{"name":"Vietnam","weight":0.4422},{"name":"Turkey","weight":0.1151},{"name":"UAE","weight":0.2243}],"reels":[{"title":"Trading: what most people get wrong","likes":156},{"title":"Onchain breakdown of this week's flows","likes":117}]},
  {"rank":15,"name":"Sam Whitfield","username":"dao_dora","bio":"Bitcoin • L2 & scaling explainers. Builder-friendly. Rollups, data availability, ZK.","followers":111350,"engagementRate":0.0262,"fakeFollowers":0.1249,"averageReelPlays":16305,"location":"South Korea","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio14","platform":"x","niche":"Bitcoin","gender":[{"label":"male","value":0.7684},{"label":"female","value":0.2316}],"countries":[{"name":"Brazil","weight":0.4376},{"name":"United States","weight":0.1747},{"name":"Vietnam","weight":0.2129},{"name":"South Korea","weight":0.0937},{"name":"Turkey","weight":0.0811}],"reels":[{"title":"Bitcoin: what most people get wrong","likes":2334},{"title":"Onchain breakdown of this week's flows","likes":1750}]},
  {"rank":16,"name":"Maya Iqbal","username":"rollup_rio","bio":"Gaming / GameFi • Onchain analytics. Wallet flows, smart-money tracking, dashboards.","followers":59834,"engagementRate":0.0176,"fakeFollowers":0.0151,"averageReelPlays":30106,"location":"Germany","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio15","platform":"x","niche":"Gaming / GameFi","gender":[{"label":"male","value":0.5446},{"label":"female","value":0.4554}],"countries":[{"name":"Japan","weight":0.2943},{"name":"UAE","weight":0.2472},{"name":"Turkey","weight":0.0479},{"name":"United States","weight":0.0872},{"name":"Vietnam","weight":0.3234}],"reels":[{"title":"Gaming / GameFi: what most people get wrong","likes":842},{"title":"Onchain breakdown of this week's flows","likes":632}]},
  {"rank":17,"name":"Arda Demir","username":"staking_sam","bio":"Memecoins • Bitcoin-first. Self-custody, Lightning, and sovereignty. Stack sats.","followers":111577,"engagementRate":0.0385,"fakeFollowers":0.133,"averageReelPlays":30815,"location":"France","verified":false,"picture":"https://i.pravatar.cc/200?u=kolio16","platform":"tiktok","niche":"Memecoins","gender":[{"label":"male","value":0.5873},{"label":"female","value":0.4127}],"countries":[{"name":"Vietnam","weight":0.5819},{"name":"France","weight":0.0538},{"name":"Japan","weight":0.0475},{"name":"Turkey","weight":0.0934},{"name":"Brazil","weight":0.2234}],"reels":[{"title":"Memecoins: what most people get wrong","likes":3437},{"title":"Onchain breakdown of this week's flows","likes":2577}]},
  {"rank":18,"name":"Leo Marchetti","username":"mint_maya","bio":"Research • DeFi research & yield strategies. Threads on protocol risk. No financial advice.","followers":84031,"engagementRate":0.0158,"fakeFollowers":0.0892,"averageReelPlays":20324,"location":"United States","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio17","platform":"tiktok","niche":"Research","gender":[{"label":"male","value":0.4761},{"label":"female","value":0.5239}],"countries":[{"name":"UAE","weight":0.5942},{"name":"United Kingdom","weight":0.1437},{"name":"Vietnam","weight":0.0045},{"name":"United States","weight":0.1035},{"name":"South Korea","weight":0.1541}],"reels":[{"title":"Research: what most people get wrong","likes":1062},{"title":"Onchain breakdown of this week's flows","likes":797}]},
  {"rank":19,"name":"Hana Kim","username":"alpha_arda","bio":"RWA • GameFi & on-chain gaming. Reviews, playtests, and tokenomics teardowns.","followers":360242,"engagementRate":0.0419,"fakeFollowers":0.0234,"averageReelPlays":194707,"location":"Germany","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio18","platform":"tiktok","niche":"RWA","gender":[{"label":"male","value":0.6371},{"label":"female","value":0.3629}],"countries":[{"name":"Japan","weight":0.3304},{"name":"Germany","weight":0.2242},{"name":"South Korea","weight":0.2624},{"name":"United States","weight":0.0405},{"name":"Vietnam","weight":0.1425}],"reels":[{"title":"RWA: what most people get wrong","likes":12075},{"title":"Onchain breakdown of this week's flows","likes":9056}]},
  {"rank":20,"name":"Tariq Aziz","username":"ledger_leo","bio":"Stablecoins • Stablecoins & payments. RWA, treasuries, and the on-chain dollar.","followers":3140635,"engagementRate":0.0645,"fakeFollowers":0.0792,"averageReelPlays":1718638,"location":"Japan","verified":true,"picture":"https://i.pravatar.cc/200?u=kolio19","platform":"tiktok","niche":"Stablecoins","gender":[{"label":"male","value":0.7618},{"label":"female","value":0.2382}],"countries":[{"name":"United States","weight":0.231},{"name":"South Korea","weight":0.1139},{"name":"United Kingdom","weight":0.3772},{"name":"Germany","weight":0.1451},{"name":"Nigeria","weight":0.1328}],"reels":[{"title":"Stablecoins: what most people get wrong","likes":162057},{"title":"Onchain breakdown of this week's flows","likes":121543}]},
];
