// Kolio editorial — "Best Web3 KOL Marketing Platforms" comparison.
// All external product screenshots removed (img left empty), so PlatformSection renders
// the clean text block instead of an external image.
export interface Platform {
  num: number; name: string; short: string;
  glance: [string, string][];
  whatis: string; strengths: string[]; weaknesses: string[];
  img: string; further: string;
}
export const PLATFORMS: Platform[] = [
  {
    num: 1, name: "Kolio", short: "Kolio",
    glance: [
      ["Best for", "Crypto and web3 brands that want web2-grade rigor when running campaigns with KOLs"],
      ["Free trial", "Yes, 14 days, with usage limits."],
      ["Price", "Paid plans start at $199/month (paid annually) or $299/month (paid monthly). 👉 Kolio Plans & Pricing"],
      ["Platforms", "X/Twitter, YouTube, TikTok, Telegram"],
      ["KOL coverage", "Proof-verified KOLs across DeFi, L1/L2, NFTs, trading, and gaming"],
      ["Used by", "Exchanges, L2s, DeFi protocols, and launch-stage projects"],
      ["Review score", "★ 4.9/5 (Capterra), ★ 5/5 (Product Hunt), ★ 4.9/5 (G2)"],
    ],
    whatis: "Kolio is the web3 influencer marketing platform. We took everything that made web2 creator platforms work — proof-based vetting, real audience data, clean campaign workflows, accountable payments — and rebuilt it for crypto KOLs. You can discover KOLs across X, YouTube, TikTok, and Telegram, verify their real reach and audience quality (not vanity metrics or follower counts), run the campaign, settle payment through on-chain escrow, and attribute on-chain conversions — all without leaving a single tab. Here's a look at Kolio's core features…",
    strengths: [
      "Run paid partnerships, sponsored threads, AMA pushes, and ambassador programs from one place.",
      "Settle every deal through on-chain escrow — funds release on verified delivery, so neither side has to trust the other on faith.",
      "Proof-based vetting surfaces a KOL's real reach and audience quality, so you stop paying for bought followers and engagement pods.",
      "Monthly pricing makes it easy to spin up around a single TGE, listing, or launch window and pause between campaigns.",
    ],
    weaknesses: ["Focused on crypto KOLs — if you need mainstream web2 lifestyle creators, a general influencer tool will serve you better."],
    img: "", further: "",
  },
  {
    num: 2, name: "Traackr", short: "Traackr",
    glance: [["Best for", "Enterprise influencer management for large consumer brands"], ["Free trial", "No"], ["Price", "From $32,500 per year"], ["Platforms", "Mostly web2 social (Traackr says it covers 13 platforms)"], ["KOL coverage", "Limited crypto-native coverage"], ["Used by", "Lacoste, L’Oreal, Samsung"], ["Review score", "★ 4.3/5 (G2), ★ 4.6/5 (Capterra), ★ 7.7/10 (TrustRadius)"]],
    whatis: "As one of the first influencer marketing platforms (it launched in 2008), Traackr is a mature, data-driven tool built for large web2 consumer brands. The catch for crypto teams: Traackr was never designed for KOLs on X or Telegram, has no concept of on-chain payments or attribution, and prices itself for enterprise marketing departments rather than lean web3 growth teams.",
    strengths: ["Strong metrics and benchmarking for measuring campaign ROI over time.", "Feature-rich, with gifting, product seeding, and affiliate support.", "Market-leading competitive intelligence for beauty, fashion, and consumer electronics.", "Responsive, knowledgeable customer support."],
    weaknesses: ["One of the most expensive platforms on this list — out of reach for most web3 growth budgets.", "No crypto-native KOL discovery; X and Telegram coverage is thin to nonexistent.", "No on-chain payments, escrow, or wallet-level attribution.", "Interface isn't especially intuitive."],
    img: "", further: "11 Traackr Alternatives For Web3 KOL Marketing",
  },
  {
    num: 3, name: "GRIN", short: "GRIN",
    glance: [["Best for", "Automating ecommerce creator workflows"], ["Free trial", "Yes, on request"], ["Price", "Unlisted, although Capterra says prices start at $999 per month"], ["Platforms", "Instagram, TikTok, YouTube"], ["KOL coverage", "None — ecommerce creators only"], ["Used by", "ColourPop, Skims, Vera Bradley"], ["Review score", "★ 4.5/5 (G2), ★ 4.7/5 (Capterra), ★ 6.2/10 (TrustRadius)"]],
    whatis: "GRIN is a polished creator management platform built around ecommerce product seeding and shipping. It automates a lot of workflow — communication, contracts, payments — but it's firmly a web2 tool. There's no X/Telegram KOL discovery, no on-chain settlement, and its first-party-authentication model means crypto KOLs would have to opt in before you could even work with them. For a token launch or protocol campaign, it's the wrong shape.",
    strengths: ["Automates much of the ecommerce creator lifecycle, from brief to payout.", "Deep ecommerce integrations (Shopify, WooCommerce, BigCommerce, Magento).", "AI copilot can run affiliate programs end to end.", "Well-regarded, prompt customer support."],
    weaknesses: ["No crypto KOL coverage; built for shipping physical products, not on-chain campaigns.", "Content tracking relies on creators connecting their own social accounts.", "Only captures posts that carry the exact hashtag or mention, so mistagged content slips through.", "No concept of escrow or on-chain attribution."],
    img: "", further: "12 GRIN Alternatives For Crypto KOL Campaigns",
  },
  {
    num: 4, name: "Upfluence", short: "Upfluence",
    glance: [["Best for", "Large web2 brands wanting hands-off campaigns plus agency support"], ["Free trial", "Yes"], ["Price", "Unlisted"], ["Platforms", "YouTube, Instagram, TikTok, Twitch, X/Twitter, Pinterest, blogs"], ["KOL coverage", "Some X/Twitter, but not crypto-native"], ["Used by", "Benefit, HelloFresh, Revolut"], ["Review score", "★ 4.6/5 (G2), ★ 4.2/5 (Trustpilot), ★ 4.3/5 (Capterra)"]],
    whatis: "Upfluence is an all-in-one platform for large ecommerce brands, with optional agency services. It does technically cover X/Twitter, but its database isn't built around crypto niches, and crypto KOLs in its marketplace are typically also working with dozens of other brands — which reads as inauthentic to a web3 audience. There's no on-chain payment rail and no wallet-level attribution, so for protocol and exchange campaigns it leaves the most important parts unsolved.",
    strengths: ["Solid affiliate tooling with link generation and tracking.", "Optional agency support and an opt-in Creator Marketplace.", "Integrates with Adobe Commerce, BigCommerce, Shopify, WooCommerce, Klaviyo, and more."],
    weaknesses: ["All communication is forced through Upfluence rather than your own inbox.", "Crypto-native KOL coverage is thin; users report exhausting the relevant pool quickly.", "No on-chain escrow or attribution.", "No monthly plans."],
    img: "", further: "10 Upfluence Alternatives For Web3 Growth Teams",
  },
  {
    num: 5, name: "Meltwater", short: "Meltwater",
    glance: [["Best for", "Brands wanting combined social listening and influencer tools"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, TikTok, YouTube"], ["KOL coverage", "Negligible crypto coverage"], ["Used by", "Adidas, Estée Lauder, KAYAK"], ["Review score", "★ 4/5 (G2), ★ 7.2/10 (TrustRadius), ★ 4/5 (Capterra)"]],
    whatis: "Meltwater is a broad media-intelligence suite with an influencer module bolted on. It's powerful for PR and consumer brands, but it requires creators to verify their accounts before key features work — a non-starter friction point for crypto KOLs who guard their identity. There's no X/Telegram-first discovery, no on-chain payments, and no attribution for token or app conversions.",
    strengths: ["Strong pre-hire insight into a creator's engagement and reach.", "Reporting is easy to export and share with stakeholders.", "Covers many use cases beyond influencer marketing, including media monitoring."],
    weaknesses: ["Requires creators to create accounts and authenticate — friction crypto KOLs resist.", "Steep learning curve; G2 reviewers cite difficult navigation.", "Built for web2 social channels, not X/Telegram crypto communities.", "No on-chain settlement or attribution."],
    img: "", further: "",
  },
  {
    num: 6, name: "NeoReach", short: "NeoReach",
    glance: [["Best for", "Deep analytics with optional agency services"], ["Free trial", "No"], ["Price", "Software plans start around $1,500 per month"], ["Platforms", "Instagram, TikTok, YouTube, Twitch, X/Twitter, Snapchat, Facebook"], ["KOL coverage", "Some X/Twitter, limited crypto niche depth"], ["Used by", "Airbnb, Honda, Walmart"], ["Review score", "★ 4.5/5 (G2), ★ 4.8/5 (Featured Customers)"]],
    whatis: "NeoReach is primarily an agency that also licenses its analytics software. The analytics are genuinely strong, and it does index X/Twitter, but it has no crypto-niche taxonomy (DeFi vs L2 vs gaming), no on-chain payments, and no token attribution. If you have a large budget and want a managed service for a web2-leaning campaign, it can work; for self-serve web3 KOL campaigns, it's a poor fit.",
    strengths: ["Strong search and filtering for macro-creators.", "Managed agency option for hands-off teams.", "Deep analytics drawing on 400+ data endpoints."],
    weaknesses: ["Pricing is prohibitive for smaller web3 teams.", "Minimum one-year commitment; no monthly plans.", "No crypto-niche segmentation, on-chain escrow, or attribution."],
    img: "", further: "",
  },
  {
    num: 7, name: "Later Influence", short: "Later",
    glance: [["Best for", "Enterprise consumer brands wanting managed services"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, Facebook, TikTok, Pinterest, X/Twitter"], ["KOL coverage", "Minimal crypto-native coverage"], ["Used by", "American Girl, GoPro, Pottery Barn"], ["Review score", "★ 4.5/5 (G2), ★ 4.6/5 (Capterra), ★ 8.2/10 (TrustRadius)"]],
    whatis: "Later is best known as a social scheduling tool that acquired the influencer platform Mavrck and rebranded it as Later Influence. It's a competent end-to-end web2 tool — discovery, campaigns, gifting, payments — but its database and tracking skew toward Instagram and TikTok lifestyle creators. There's no crypto KOL focus, no on-chain settlement, and no token-level attribution.",
    strengths: [],
    weaknesses: ["Discovery skews to web2 lifestyle creators; crypto KOL coverage is thin.", "Automated tracking only captures live posts on Instagram and TikTok — not X or Telegram.", "Hard to find niche, crypto-native creators.", "No on-chain escrow or attribution.", "No monthly plans."],
    img: "", further: "",
  },
  {
    num: 8, name: "HypeAuditor", short: "HypeAuditor",
    glance: [["Best for", "Audience-quality analytics across many platforms"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, TikTok, YouTube, Twitch, X/Twitter"], ["KOL coverage", "Indexes X/Twitter; no crypto-niche depth"], ["Used by", "Dior, H&M, Philips"], ["Review score", "★ 4.6/5 (G2), ★ 4.3/5 (Product Hunt), ★ 4.8/5 (Capterra)"]],
    whatis: "HypeAuditor is a strong analytics-first platform with a deep focus on audience quality and fake-follower detection — genuinely useful signals for vetting KOLs. It indexes X/Twitter and offers some end-to-end workflow. But it has no crypto-niche taxonomy, payments run through PayPal rather than on-chain rails, and there's no token or wallet attribution, so the crypto-specific parts of a campaign live outside the tool.",
    strengths: ["Extensive analytics — audience quality, engagement, growth, and more.", "Large profile database across five social networks.", "Clean, relatively intuitive interface."],
    weaknesses: ["No on-chain payment rail — payouts run through PayPal, adding fees for KOLs.", "No crypto-niche segmentation or token attribution.", "Some estimated-pricing metrics produce misleading results.", "Data can be hard to navigate and interpret."],
    img: "", further: "11 HypeAuditor Alternatives For Vetting Crypto KOLs",
  },
  {
    num: 9, name: "CreatorIQ", short: "CreatorIQ",
    glance: [["Best for", "Enterprise analytics and reporting"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, YouTube, TikTok, Facebook, Pinterest"], ["KOL coverage", "None — web2 enterprise creators"], ["Used by", "CVS, Nestle, Unilever"], ["Review score", "★ 4.7/5 (Cuspera), ★ 4.6/5 (G2), ★ 4.4/5 (Capterra)"]],
    whatis: "CreatorIQ is one of the most sophisticated enterprise creator platforms, with strong analytics and a deep integration stack. It's built for large web2 marketing organizations, though — there's no X/Telegram-first crypto discovery, no on-chain payments, and a steep learning curve that lean web3 teams rarely have time for.",
    strengths: [],
    weaknesses: ["No crypto KOL coverage; built for web2 enterprise programs.", "Search frequently surfaces irrelevant results.", "Steeper learning curve than most; 'complexity' is a common complaint.", "No on-chain settlement or attribution.", "No monthly plans."],
    img: "", further: "10 CreatorIQ Alternatives For Better Flexibility",
  },
  {
    num: 10, name: "Impact", short: "Impact",
    glance: [["Best for", "Affiliate and partnership programs"], ["Free trial", "Yes, 30 days"], ["Price", "From $30 per month or 2.5% of monthly revenue, whichever is greater"], ["Platforms", "n/a"], ["KOL coverage", "Small vetted marketplace, web2-leaning"], ["Used by", "Canva, eBay, HubSpot"], ["Review score", "★ 4.5/5 (G2), ★ 4.6/5 (Shopify), ★ 6.3/10 (TrustRadius)"]],
    whatis: "Impact is rooted in affiliate and performance marketing and has grown into a broad partnership management platform. It's good at affiliate attribution in a web2 sense, but its creator marketplace is small and web2-leaning, it can feel bloated, and it has no native concept of on-chain escrow or wallet-level conversion tracking. Look closely at your needs before assuming it covers crypto KOL work.",
    strengths: ["Automates affiliate recruitment and outreach.", "Powerful campaign analytics and reporting.", "Responsive, knowledgeable support.", "Integrates with Shopify, BigCommerce, WooCommerce, and more."],
    weaknesses: ["UI is widely described as unintuitive.", "Small, web2-leaning creator marketplace — easy to exhaust.", "Pricing can be expensive and hard to predict.", "No on-chain escrow or token attribution."],
    img: "", further: "",
  },
  {
    num: 11, name: "#paid", short: "#paid",
    glance: [["Best for", "Brands that amplify a few creators with paid ads"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, YouTube, Snapchat, Facebook, X/Twitter"], ["KOL coverage", "Opt-in marketplace, not crypto-native"], ["Used by", "H&M, Johnson & Johnson, Philips"], ["Review score", "★ 4.7/5 (G2), ★ 4.6/5 (Capterra)"]],
    whatis: "#paid takes a matching approach instead of search: you post a brief and creators 'raise a hand.' It's a clean experience with transparent pricing, but the opt-in pool is small and web2-leaning, so finding crypto-native KOLs in a specific niche is hard. There's no on-chain settlement and no token attribution, and the matching model doesn't scale to a full launch campaign.",
    strengths: ["Clean, elegant, easy-to-use interface.", "Transparent creator pricing up front.", "Turn creator content into paid ads easily.", "Match based on lifestyle data."],
    weaknesses: ["Small opt-in pool — crypto KOLs are scarce and likely working with many other brands.", "No on-chain payments, escrow, or attribution.", "Matching model doesn't scale to launch-grade campaigns."],
    img: "", further: "",
  },
  {
    num: 12, name: "Heepsy", short: "Heepsy",
    glance: [["Best for", "Basic, low-cost creator search"], ["Free trial", "No"], ["Price", "Free search plan; paid plans from $89 per month"], ["Platforms", "Instagram, TikTok, YouTube"], ["KOL coverage", "Web2 creators; little crypto depth"], ["Used by", "Birchbox, Carl’s Jr, Uber Eats"], ["Review score", "★ 4.5/5 (Capterra), ★ 4.9/5 (ProductHunt), ★ 4.5/5 (G2)"]],
    whatis: "Heepsy is a budget-friendly creator search tool with a generous free tier — fine for a first experiment, but limited. It has no X/Telegram crypto KOL discovery, no on-chain payments, and tracking is largely Instagram-only. Its higher tiers jump to $249–$369/month, at which point better-fit web3 tools (like Kolio) make more sense.",
    strengths: ["Generous free plan to test creator search.", "Simple, easy-to-navigate basic search.", "Decent baseline creator data (location, engagement, follower count)."],
    weaknesses: ["No crypto KOL coverage; strongest in Spain, thin elsewhere.", "Only captures Instagram content automatically.", "Starter plan lacks advanced filters.", "No on-chain payments or attribution."],
    img: "", further: "10 Heepsy Alternatives For Web3 KOL Discovery",
  },
  {
    num: 13, name: "Aspire", short: "Aspire",
    glance: [["Best for", "End-to-end ecommerce creator programs with big budgets"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Facebook, Instagram, Pinterest, TikTok, YouTube, blogs"], ["KOL coverage", "Web2 creators only"], ["Used by", "Dyson, HelloFresh, Walmart"], ["Review score", "★ 4.5/5 (Capterra), ★ 4.5/5 (G2)"]],
    whatis: "Aspire is a capable end-to-end platform for ecommerce brands, with an opt-in marketplace and campaign tooling. It's a web2 tool through and through — no crypto KOL focus, PayPal-only payouts rather than on-chain settlement, and content tracking that leans on creators tagging the brand correctly. G2 data also pegs it as pricier than average.",
    strengths: ["Strong feature set and ecommerce integrations.", "Well-regarded success team.", "Broad web2 creator coverage across niches."],
    weaknesses: ["No crypto KOL coverage; payouts via PayPal only.", "Tracking depends on creators tagging correctly.", "No on-chain escrow or token attribution.", "Pricier than the category average."],
    img: "", further: "10 Aspire Alternatives For Crypto KOL Marketing",
  },
  {
    num: 14, name: "Captiv8", short: "Captiv8",
    glance: [["Best for", "Creator tools with built-in social listening"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "TikTok, Facebook, Instagram, X/Twitter, YouTube"], ["KOL coverage", "Indexes X but not crypto-native"], ["Used by", "American Express, Levi’s, Zara"], ["Review score", "★ 4.7/5 (G2)"]],
    whatis: "Captiv8 started as a social-listening tool and grew into a creator platform aimed at mid-to-large brands and agencies. Its listening features are useful for brand reputation, and it indexes X/Twitter, but it has no crypto-niche segmentation, no on-chain payment rail, and no token attribution. For pure web3 KOL recruitment and settlement, it's heavier than it needs to be.",
    strengths: ["Smart social listening across your brand and competitors.", "Detailed audience demographics and brand-affinity insight.", "Integrates with major ecommerce tools."],
    weaknesses: ["No crypto-niche taxonomy or crypto-native KOL pool.", "Filter-only search with no natural-language discovery.", "No on-chain escrow or attribution."],
    img: "", further: "8 Captiv8 Alternatives (And When to Choose Them)",
  },
  {
    num: 15, name: "Influencity", short: "Influencity",
    glance: [["Best for", "TikTok and Instagram creator search"], ["Free trial", "Yes, seven days"], ["Price", "From $398 per month"], ["Platforms", "Instagram, TikTok, YouTube"], ["KOL coverage", "Web2 creators; no crypto niche"], ["Used by", "Air France, Pernod Ricard, Samsung"], ["Review score", "★ 4.6/5 (G2), ★ 4.8/5 (Product Hunt), ★ 4.2/5 (Capterra)"]],
    whatis: "Influencity offers solid discovery, analytics, and campaign management for Instagram, TikTok, and YouTube, with strong vetting data points. The gap for crypto teams is structural: it doesn't index X/Twitter or Telegram, has no crypto-niche taxonomy, and offers no on-chain payments or attribution. It's a good web2 tool that simply wasn't built for KOLs.",
    strengths: ["Large web2 creator database with deep TikTok coverage.", "20+ vetting data points, including fake-follower analysis.", "Strong list and relationship management."],
    weaknesses: ["No X/Telegram coverage and no crypto-niche segmentation.", "Can't auto-track Instagram Stories or YouTube Shorts.", "No on-chain payments or token attribution."],
    img: "", further: "10 Influencity Alternatives For KOL Discovery",
  },
  {
    num: 16, name: "Julius", short: "Julius",
    glance: [["Best for", "Seeing creator fees before reaching out"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, Facebook, YouTube, TikTok, Snapchat, Pinterest, X/Twitter, Twitch"], ["KOL coverage", "Indexes X but not crypto-native"], ["Used by", "Club Med, Dentsu, New York Islanders"], ["Review score", "★ 4.5/5 (GetApp), ★ 4.5/5 (G2)"]],
    whatis: "Julius is a broad creator database (owned by Triller) covering most web2 social platforms, with handy upfront fee data. It indexes X/Twitter but has no crypto-niche depth, no way to pay creators on-chain, and no token attribution. It's almost end-to-end for web2 — but you'd handle every crypto-specific part of the campaign elsewhere.",
    strengths: ["Clean UI with readable creator profiles.", "Shows creator fees up front for faster budgeting.", "Wide platform coverage, including Pinterest and Twitch."],
    weaknesses: ["Opaque — no public pricing and no stated database size.", "No crypto-niche segmentation; thin even in some mature markets.", "Steep learning curve.", "No way to pay KOLs through the platform, on-chain or otherwise."],
    img: "", further: "",
  },
  {
    num: 17, name: "Sprout Social Influencer Marketing", short: "Sprout Social Influencer Marketing",
    glance: [["Best for", "Lots of search filters and integrations"], ["Free trial", "No"], ["Price", "Unlisted"], ["Platforms", "Instagram, YouTube, Facebook, TikTok, X/Twitter, Twitch"], ["KOL coverage", "Indexes X but not crypto-native"], ["Used by", "KISS, Trello"], ["Review score", "★ 4.3/5 (G2)"]],
    whatis: "Sprout Social's influencer module (formerly Tagger) is built around data and reporting, with 50+ search filters. It covers six social platforms and indexes X/Twitter, but the pool is web2-leaning and there's no crypto-niche taxonomy, no on-chain settlement, and no token attribution. Consider it only if deep reporting is your single biggest need.",
    strengths: ["Real-time data on engagement, reach, and conversions.", "Integrates with a wide range of third-party tools."],
    weaknesses: ["Web2-leaning pool with no crypto-niche segmentation.", "Some usability and outreach complaints.", "Reports of data-accuracy issues.", "No on-chain escrow or attribution."],
    img: "", further: "",
  },
  {
    num: 18, name: "Bazaarvoice Vibe Creator Marketing", short: "Bazaarvoice Vibe Creator Marketing",
    glance: [["Best for", "Capturing and promoting user-generated content"], ["Free trial", "Yes, on request"], ["Price", "Unlisted"], ["Platforms", "Instagram, YouTube, Facebook, TikTok, X/Twitter"], ["KOL coverage", "None — UGC and reviews focus"], ["Used by", "Clarins, Feelunique, Target"], ["Review score", "★ 4.2/5 (G2), ★ 8.3/10 (TrustRadius), ★ 4.3/5 (Capterra)"]],
    whatis: "Creator marketing is a small part of Bazaarvoice, which is really a user-generated-content and reviews suite. You can search and run creator campaigns, but it's optimized for ratings, reviews, and FAQ content — not crypto KOLs. There's no X/Telegram-first discovery, no on-chain payments, and no token attribution.",
    strengths: ["Does far more than influencer marketing — UGC, reviews, social commerce.", "Integrates with Shopify, Salesforce Commerce Cloud, and Spryker.", "User-friendly for non-technical marketers.", "AI-assisted creator search."],
    weaknesses: ["No crypto KOL coverage; built around reviews and UGC.", "No tools to pay creators, on-chain or otherwise.", "Smaller-than-average creator database."],
    img: "", further: "",
  },
  {
    num: 19, name: "TrendHero", short: "TrendHero",
    glance: [["Best for", "Affordable Instagram-only search and analytics"], ["Free trial", "No"], ["Price", "Free analytics plan; paid plans from $15.99 per month"], ["Platforms", "Instagram only"], ["KOL coverage", "None — Instagram only"], ["Used by", "Arena, Franklin, Hyatt"], ["Review score", "★ 4.3/5 (G2)"]],
    whatis: "TrendHero is an affordable, Instagram-only analytics and search tool — a reasonable starter for small web2 brands. For web3 it's simply out of scope: Instagram-only means no X, YouTube, TikTok, or Telegram coverage, no crypto KOL pool, and no on-chain payments or attribution.",
    strengths: ["Clean, simple UI that's quick to start.", "19 search filters for Instagram.", "Larger Instagram database than some pricier tools."],
    weaknesses: ["Instagram only — no X, YouTube, TikTok, or Telegram.", "No crypto KOL coverage.", "No campaign management, on-chain payments, or attribution."],
    img: "", further: "",
  },
];
